# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_analysis_state_signature"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodelregistry",
            name="cluster_selection",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Kurva seleksi jumlah cluster: list {k, silhouette, inertia} "
                    "untuk k=2..MAX_CLUSTERS. Dipakai untuk transparansi pemilihan k."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="mlmodelregistry",
            name="feature_importance",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Importance per indikator (eta-squared antar-cluster), "
                    "diurutkan dari yang paling dominan."
                ),
            ),
        ),
    ]
