# Generated by Django 5.2.16 on 2026-08-25 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0007_village_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourismCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Tourism Category",
                "verbose_name_plural": "Tourism Categories",
                "db_table": "gis_tourism_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegionElevation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "min_elevation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Minimum Elevation (m)"
                    ),
                ),
                (
                    "max_elevation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Maximum Elevation (m)"
                    ),
                ),
                (
                    "mean_elevation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Mean Elevation (m)"
                    ),
                ),
                (
                    "median_elevation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Median Elevation (m)"
                    ),
                ),
                (
                    "std_deviation",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Standard Deviation (m)"
                    ),
                ),
                (
                    "source_dataset",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contoh: DEMNAS 8m, SRTM 30m, dsb.",
                        max_length=200,
                        verbose_name="Source Dataset",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contoh: 8m, 30m, 90m.",
                        max_length=50,
                        verbose_name="Resolution",
                    ),
                ),
                (
                    "village",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elevation",
                        to="master.village",
                        verbose_name="Village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region Elevation",
                "verbose_name_plural": "Region Elevations",
                "db_table": "gis_region_elevation",
            },
        ),
        migrations.CreateModel(
            name="TouristDestination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Name"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "tourism_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Tipe utama (mis. alam, air terjun, budaya).",
                        max_length=50,
                        verbose_name="Tourism Type",
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Estimated Duration (minutes)",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Opening Time"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Closing Time"
                    ),
                ),
                (
                    "ticket_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Ticket Price (IDR)",
                    ),
                ),
                (
                    "parking_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Parking Cost (IDR)",
                    ),
                ),
                (
                    "accessibility",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Deskripsi aksesibilitas umum (teks bebas).",
                        verbose_name="Accessibility",
                    ),
                ),
                (
                    "accessibility_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detail terstruktur (kendaraan, akses mobil/motor, jalan sempit, medan, tangga, fasilitas lansia, toilet, dll.).",
                        verbose_name="Accessibility Details",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("easy", "Mudah"),
                            ("moderate", "Sedang"),
                            ("hard", "Sulit"),
                        ],
                        default="",
                        max_length=30,
                        verbose_name="Difficulty",
                    ),
                ),
                (
                    "family_friendly",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Family Friendly"
                    ),
                ),
                (
                    "elderly_friendly",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Elderly Friendly"
                    ),
                ),
                (
                    "child_friendly",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Child Friendly"
                    ),
                ),
                (
                    "indoor_outdoor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("indoor", "Dalam Ruangan"),
                            ("outdoor", "Luar Ruangan"),
                            ("both", "Dalam & Luar Ruangan"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Indoor / Outdoor",
                    ),
                ),
                (
                    "facilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List fasilitas, mis. ['toilet', 'parkir', 'warung'].",
                        verbose_name="Facilities",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Source"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="destinations",
                        to="gis.tourismcategory",
                        verbose_name="Categories",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opsional; biasanya mengikuti kecamatan desa.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destinations",
                        to="master.district",
                        verbose_name="District",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destinations",
                        to="master.village",
                        verbose_name="Village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tourist Destination",
                "verbose_name_plural": "Tourist Destinations",
                "db_table": "gis_tourist_destination",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RegionCharacteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "characteristic_type",
                    models.CharField(
                        db_index=True,
                        help_text="Kategori, contoh: geography, economy, culture, tourism_potential, facility, accessibility, commodity.",
                        max_length=50,
                        verbose_name="Characteristic Type",
                    ),
                ),
                (
                    "characteristic_name",
                    models.CharField(
                        db_index=True,
                        help_text="Contoh: ketinggian, luas wilayah, komoditas, potensi wisata.",
                        max_length=100,
                        verbose_name="Characteristic Name",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text="Nilai karakteristik (teks bebas).",
                        verbose_name="Value",
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="Value Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Source"
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="characteristics",
                        to="master.village",
                        verbose_name="Village",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region Characteristic",
                "verbose_name_plural": "Region Characteristics",
                "db_table": "gis_region_characteristic",
                "ordering": ["characteristic_type", "characteristic_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "village",
                            "characteristic_type",
                            "characteristic_name",
                        ),
                        name="uniq_region_characteristic",
                    )
                ],
            },
        ),
    ]
