# Generated by Django 5.2.16 on 2026-08-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="touristdestination",
            name="ticket_price",
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="ticket_price_weekday",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Harga tiket hari Senin–Jumat.",
                max_digits=12,
                null=True,
                verbose_name="Ticket Price Weekday (IDR)",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="ticket_price_weekend",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Harga tiket hari Sabtu–Minggu.",
                max_digits=12,
                null=True,
                verbose_name="Ticket Price Weekend (IDR)",
            ),
        ),
    ]
