# Generated by Django 5.2.16 on 2026-08-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0002_remove_touristdestination_ticket_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristdestination",
            name="closed_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List hari tutup (0=Senin … 6=Minggu). Kosong = buka setiap hari, null = belum diketahui.",
                null=True,
                verbose_name="Hari Tutup",
            ),
        ),
    ]
