# Generated by Django 5.2.16 on 2026-08-27 06:49

from django.db import migrations, models


def backfill_ticket_type(apps, schema_editor):
    """
    Data lama belum punya ``ticket_type``/``price_source``. Isi ulang:
    - destinasi yang punya harga (weekday/weekend/parkir) -> "fixed"
    - sisanya -> "unknown" (belum diketahui, BUKAN gratis)
    """
    TouristDestination = apps.get_model("gis", "TouristDestination")

    priced = TouristDestination.objects.exclude(
        ticket_price_weekday__isnull=True,
        ticket_price_weekend__isnull=True,
        parking_cost__isnull=True,
    )
    priced.update(
        ticket_type="fixed",
        price_source="Manual",
        price_source_type="manual",
    )
    # Timestamp harga mengikuti waktu terakhir data diperbarui.
    for dest in priced:
        dest.price_updated_at = dest.updated_at
        dest.save(update_fields=["price_updated_at"])

    TouristDestination.objects.filter(
        ticket_price_weekday__isnull=True,
        ticket_price_weekend__isnull=True,
        parking_cost__isnull=True,
    ).update(ticket_type="unknown")


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0003_touristdestination_closed_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristdestination",
            name="category_prices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Harga per kategori (list of dict), contoh: [{"category": "Dewasa", "price": 20000}, {"category": "Anak-anak", "price": 10000}].',
                verbose_name="Category Prices",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="is_open_24_hours",
            field=models.BooleanField(
                default=False,
                help_text="Centang bila destinasi buka 24 jam. UI/chatbot akan menampilkan 'Buka 24 jam', bukan 00:00–23:59.",
                verbose_name="Open 24 Hours",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="price_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Deskripsi harga untuk ditampilkan, mis. 'Dewasa Rp20.000, Anak-anak Rp10.000'.",
                verbose_name="Price Description",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="price_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nama sumber harga, mis. 'Manual', 'Traveloka', 'Website Resmi'.",
                max_length=200,
                verbose_name="Price Source",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="price_source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("scraping", "Scraping/API"),
                    ("other", "Lainnya"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Price Source Type",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="price_source_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL sumber harga (jika ada).",
                verbose_name="Price Source URL",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="price_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Price Updated At"
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="status_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Alasan destinasi nonaktif (mis. sedang renovasi, tutup sementara). Wajib diisi bila status Nonaktif.",
                max_length=255,
                verbose_name="Status Reason",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="status_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Status Updated At"
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Belum diketahui"),
                    ("free", "Gratis"),
                    ("fixed", "Harga tetap"),
                    ("category", "Per kategori"),
                ],
                default="unknown",
                help_text="'Gratis' untuk destinasi tanpa tiket, 'Harga tetap' untuk angka tunggal, 'Per kategori' bila ada beberapa harga, 'Belum diketahui' bila belum ada data.",
                max_length=20,
                verbose_name="Ticket Type",
            ),
        ),
        migrations.RunPython(
            backfill_ticket_type,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
