# Generated by Django 5.2.16 on 2026-08-27 07:50

from django.db import migrations, models


def backfill_is_free(apps, schema_editor):
    """
    Migrasi data: nilai ``ticket_type="free"`` lama dipindah ke field
    ``is_free`` (checkbox) yang baru.
    """
    TouristDestination = apps.get_model("gis", "TouristDestination")
    TouristDestination.objects.filter(ticket_type="free").update(
        is_free=True,
        ticket_type="unknown",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0004_touristdestination_category_prices_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristdestination",
            name="is_free",
            field=models.BooleanField(
                default=False,
                help_text="Centang bila destinasi GRATIS (tanpa tiket). Kolom harga akan diabaikan.",
                verbose_name="Gratis",
            ),
        ),
        migrations.AlterField(
            model_name="touristdestination",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("unknown", "Belum diketahui"),
                    ("fixed", "Harga tetap"),
                    ("category", "Per kategori"),
                ],
                default="unknown",
                help_text="'Harga tetap' untuk angka tunggal, 'Per kategori' bila ada beberapa harga, 'Belum diketahui' bila belum ada data.",
                max_length=20,
                verbose_name="Ticket Type",
            ),
        ),
        migrations.RunPython(
            backfill_is_free,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
