# Generated by Django 5.2.16 on 2026-08-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0005_touristdestination_is_free_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristdestination",
            name="price_source_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("scraping", "Scraping/API"),
                    ("other", "Lainnya"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Price Source Type",
            ),
        ),
    ]
