# Generated by Django 5.2.16 on 2026-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0006_alter_touristdestination_price_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristdestination",
            name="ticket_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unknown", "Belum diketahui"),
                    ("fixed", "Harga tetap"),
                    ("category", "Per kategori"),
                ],
                default="unknown",
                help_text="'Harga tetap' untuk angka tunggal, 'Per kategori' bila ada beberapa harga, 'Belum diketahui' bila belum ada data.",
                max_length=20,
                verbose_name="Ticket Type",
            ),
        ),
    ]
