# Generated by Django 5.2.16 on 2026-08-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0007_alter_touristdestination_ticket_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristdestination",
            name="is_free_parking",
            field=models.BooleanField(
                default=False,
                help_text="Centang bila parkir GRATIS. Kolom biaya parkir akan diabaikan.",
                verbose_name="Bebas Biaya Parkir",
            ),
        ),
    ]
