# Generated by Django 5.2.16 on 2026-08-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0008_touristdestination_is_free_parking"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristdestination",
            name="ride_prices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Harga wahana/atraksi tambahan (list of dict), contoh: [{"name": "Flying Fox", "price": 25000}, {"name": "ATV", "price": 50000}].',
                verbose_name="Harga per Wahana",
            ),
        ),
    ]
