# Generated by Django 5.2.16 on 2026-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0009_touristdestination_ride_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristdestination",
            name="bundle_prices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Paket tiket bundle (list of dict), contoh: [{"name": "Paket Hemat", "includes_htm": true, "rides": ["Flying Fox"], "price": 50000}].',
                verbose_name="Bundle Prices",
            ),
        ),
    ]
