# Generated by Django 5.2.16 on 2026-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0010_touristdestination_bundle_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristdestination",
            name="elevation_meters",
            field=models.FloatField(
                blank=True,
                help_text="Ketinggian (mdpl) hasil ekstraksi DEM.",
                null=True,
                verbose_name="Elevation (m)",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="elevation_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sumber DEM, mis. 'DEMNAS', 'ALOS PALSAR'.",
                max_length=100,
                verbose_name="Elevation Source",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="temperature_c",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Temperature (°C)"
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="temperature_date",
            field=models.DateField(
                blank=True,
                help_text="Tanggal/periode data suhu.",
                null=True,
                verbose_name="Temperature Date",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="temperature_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sumber data suhu, mis. 'BMKG', 'WorldClim'.",
                max_length=100,
                verbose_name="Temperature Source",
            ),
        ),
    ]
