# Generated by Django 5.2.16 on 2026-08-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0013_remove_legacy_json_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristdestination",
            name="google_maps_query",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Query pencarian Google Maps manual, mis. 'Batu Love Garden BALOGA, Kota Batu'. Bila kosong, sistem memakai nama + desa + Kota Batu.",
                max_length=300,
                verbose_name="Google Maps Query",
            ),
        ),
        migrations.AlterField(
            model_name="wahana",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Wajib diisi hanya bila kategori = Berbayar (Harga Sendiri).",
                max_digits=12,
                null=True,
                verbose_name="Harga (IDR)",
            ),
        ),
        migrations.AlterField(
            model_name="wahana",
            name="pricing_type",
            field=models.CharField(
                choices=[
                    ("INCLUDED_IN_HTM", "Termasuk HTM"),
                    ("INDEPENDENT_PRICE", "Berbayar (Harga Sendiri)"),
                    ("INCLUDED_IN_PACKAGE", "Termasuk Paket / Tiket"),
                    ("PRICE_UNKNOWN", "Harga Belum Tersedia"),
                ],
                default="PRICE_UNKNOWN",
                help_text="'Termasuk HTM' = sudah tercakup tiket masuk; 'Berbayar (Harga Sendiri)' = ada biaya tambahan; 'Termasuk Paket/Tiket' = harga mengikuti bundle, tanpa harga independen; 'Harga Belum Tersedia' = datanya belum ada (bukan gratis).",
                max_length=20,
                verbose_name="Kategori Harga",
            ),
        ),
        migrations.CreateModel(
            name="ParkingFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        db_index=True,
                        help_text="Contoh: Motor, Mobil, Bus, Pickup, dsb.",
                        max_length=50,
                        verbose_name="Jenis Kendaraan",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Biaya Parkir (IDR)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Catatan"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parking_fees",
                        to="gis.touristdestination",
                        verbose_name="Destinasi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biaya Parkir",
                "verbose_name_plural": "Biaya Parkir",
                "db_table": "gis_parking_fee",
                "ordering": ["vehicle_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("destination", "vehicle_type"),
                        name="uniq_parking_destination_vehicle",
                    )
                ],
            },
        ),
    ]
