# Generated by Django 5.2.16 on 2026-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0015_backfill_wahana_pricing_and_parking"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuisineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="Nama"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("flavor", "Cita Rasa"), ("cuisine", "Jenis Masakan")],
                        default="flavor",
                        max_length=20,
                        verbose_name="Jenis",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Deskripsi"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Cita Rasa / Jenis Masakan",
                "verbose_name_plural": "Cita Rasa / Jenis Masakan",
                "db_table": "gis_cuisine_type",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="ambiance",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mis. kasual, keluarga, formal, romantis.",
                max_length=100,
                verbose_name="Suasana",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="photo",
            field=models.URLField(blank=True, default="", verbose_name="Foto (URL)"),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="place_type",
            field=models.CharField(
                choices=[
                    ("attraction", "Destinasi Wisata"),
                    ("restaurant", "Restaurant / Tempat Makan"),
                ],
                db_index=True,
                default="attraction",
                help_text="Restaurant/tempat makan diperlakukan terpisah dari destinasi wisata (tidak punya HTM, memakai range harga makanan).",
                max_length=20,
                verbose_name="Jenis Tempat",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="price_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Batas atas range harga makanan (khusus restaurant).",
                max_digits=12,
                null=True,
                verbose_name="Harga Maksimum (IDR)",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="price_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Batas bawah range harga makanan (khusus restaurant).",
                max_digits=12,
                null=True,
                verbose_name="Harga Minimum (IDR)",
            ),
        ),
        migrations.AddField(
            model_name="touristdestination",
            name="cuisine_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="destinations",
                to="gis.cuisinetype",
                verbose_name="Cita Rasa / Jenis Masakan",
            ),
        ),
    ]
