# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis", "0018_seed_tourism_category_kuliner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristdestination",
            name="photo",
            field=models.URLField(
                blank=True,
                default="",
                max_length=500,
                verbose_name="Foto (URL)",
            ),
        ),
    ]
