# Generated by Django 5.2.16 on 2026-08-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_chatbotusage_month"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama Suara")),
                (
                    "provider",
                    models.CharField(max_length=100, verbose_name="Provider TTS"),
                ),
                (
                    "provider_voice_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Provider Voice ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="id-ID", max_length=20, verbose_name="Bahasa"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Profil Suara",
                "verbose_name_plural": "Profil Suara",
                "db_table": "chatbot_voice_profile",
                "ordering": ["name"],
            },
        ),
    ]
