# Generated by Django 5.2.16 on 2026-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0006_variable_config_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="village",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Deskripsi singkat karakteristik & keunikan desa.",
                verbose_name="Description",
            ),
        ),
    ]
